# Generated by Django 2.2.1 on 2019-09-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190911_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=8)),
                ('person', models.ManyToManyField(to='app01.Person')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
