# Generated by Django 2.2.1 on 2019-09-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20190912_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='num',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='salled',
        ),
        migrations.AddField(
            model_name='book',
            name='num',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='book',
            name='salled',
            field=models.IntegerField(default=10),
        ),
    ]
